### ISSUE TITLE
qtip-tip-style does not work

### ISSUE THREAD

**Issue by AnghelGabriel** [chenasraf/ng-qtip2#10]
qtip-tip-style attribute does not take effect, is there a particular way of writting thiese?

I've tried

`qtip-tip-style="{classes:'some-class'}"`

`qtip-tip-style="{width:'100px'}"`

`qtip-tip-style="{maxWidth:'100px'}"`

`qtip-tip-style="{corner:true}"`

None of them worked.
Again is there a certain way of writing these attributes?

Thanks

**Comment by AnghelGabriel** [comment]
Sorry, I just realized after writting these that the qtip-tip-style is for the small arrow :).
Closing this.

**Comment by chenasraf** [comment]
For future reference the one you were looking for is `qtip-modal-style` :)
