### ISSUE TITLE
Add qtipDefaults - which will allow to specify the default options.

### ISSUE THREAD

**Issue by idoa01** [chenasraf/ng-qtip2#5]
You currently supply `qtipOptions` but that is used to override any specific options given in the html. there is currently no way to add default options that could be overridden by other elements.

for example, in my current code, I want to use `{position: { effect: false }}` to remove the sliding effect. 

``` html
/* $ctrl.qtipDefaults =    { position: { effect: false } }; */

<div qtip="Woah!"
     qtip-my="left center"
     qtip-at="right center"
     qtip-defaults="$ctrl.qtipDefaults"></div>
```

using `qtip-options` in the code above will override `qtip-my` and `qtip-at` which is not the desired effect.

I can hack a quick pull request if you'd like.

**Comment by chenasraf** [comment]
You raised some good points. If you have something ready, I'd love a pull request - if not, I'll try to get on it before the end of the week.

**Comment by idoa01** [comment]
opened a pull request on the issue. 
take note that I removed the default `position.target` since in my (limited) test, it didn't work as expected.

two remarks on the code:
1. I noticed that you set different defaults than `qtip` does, is this on purpose? I find it kinda confusing (if you want to change that, I can just delete the `base` variable and qtip defaults will be used).
2. on `qtipOptions` I left it using `angular.extend` but I really think it should be `angular.merge` instead.

**Comment by chenasraf** [comment]
1. No real reason, this is a tool I created for my own use and just released. I didn't really check how the defaults differed, but I agree it should be merged - I'll just need to see that it doesn't break anything
2. I wasn't aware of the differences - yes, `merge` sounds much better for this case.

I'll merge, and use `angular.merge` as well.

Thanks for your contribution :)
